import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Button, FlatList, Linking, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import * as WebBrowser from 'expo-web-browser';
import * as Notifications from 'expo-notifications';
import * as DocumentPicker from 'expo-document-picker';
import { api, sessionStorage } from './src/api';
import { confirmEmail, signIn, signUp } from './src/auth';
import { registerForJobAlerts } from './src/notifications';

type Job = { jobId: string; company: string; title: string; location: string; season: string; applyUrl: string; compensation: { raw: string }; firstSeenAt: string };
type Application = { applicationId: string; jobId: string; status: string; notes?: string };
type Preference = { filter: { includeCategories?: string[]; includeKeywords?: string[] }; alertsEnabled: boolean; onboardingComplete: boolean };
const categories = ['ai-ml', 'swe', 'quant', 'product', 'design'];

function JobCard({ job, onOpen }: { job: Job; onOpen: () => void }) { return <TouchableOpacity style={styles.card} onPress={onOpen}><Text style={styles.company}>{job.company}</Text><Text style={styles.title}>{job.title}</Text><Text style={styles.muted}>{job.location} · {job.season}</Text>{job.compensation.raw ? <Text style={styles.pay}>{job.compensation.raw}</Text> : null}</TouchableOpacity>; }

export default function App() {
  const [token, setToken] = useState<string>(); const [ready, setReady] = useState(false); const [tab, setTab] = useState<'feed' | 'saved' | 'profile'>('feed'); const [preferences, setPreferences] = useState<Preference>(); const [jobs, setJobs] = useState<Job[]>([]); const [applications, setApplications] = useState<Application[]>([]); const [query, setQuery] = useState('');
  useEffect(() => { void sessionStorage.get().then((value) => { setToken(value ?? undefined); setReady(true); }); }, []);
  const load = async (idToken = token) => { if (!idToken) return; const [feed, pref, apps] = await Promise.all([api<{ jobs: Job[] }>('/jobs', ''), api<Preference>('/me/preferences', idToken), api<{ applications: Application[] }>('/me/applications', idToken)]); setJobs(feed.jobs); setPreferences(pref); setApplications(apps.applications); };
  useEffect(() => { if (token) void load(); }, [token]);
  useEffect(() => { const subscription = Notifications.addNotificationResponseReceivedListener((response) => { const jobId = response.notification.request.content.data.jobId as string | undefined; if (jobId) { setTab('feed'); void api<Job>(`/jobs/${jobId}`, '').then((job) => Alert.alert(job.title, `${job.company}\n${job.location}`, [{ text: 'Open job', onPress: () => void WebBrowser.openBrowserAsync(job.applyUrl) }])).catch(() => undefined); } }); return () => subscription.remove(); }, []);
  const filtered = useMemo(() => jobs.filter((job) => `${job.company} ${job.title} ${job.location}`.toLowerCase().includes(query.toLowerCase())), [jobs, query]);
  if (!ready) return <SafeAreaView style={styles.center}><ActivityIndicator /></SafeAreaView>;
  if (!token) return <SignIn onSession={async (idToken) => { await sessionStorage.set(idToken); setToken(idToken); }} />;
  if (!preferences?.onboardingComplete) return <Onboarding token={token} onDone={() => void load()} />;
  const apply = async (job: Job) => { const created = await api<Application>('/me/applications', token, { method: 'POST', body: JSON.stringify({ jobId: job.jobId, status: 'applied' }) }); setApplications((current) => [created, ...current]); await WebBrowser.openBrowserAsync(job.applyUrl); Alert.alert('Application tracking started', 'Complete and submit the employer’s official form. Your profile and résumé stay available in the Profile tab for manual completion.'); };
  return <SafeAreaView style={styles.screen}><View style={styles.nav}>{(['feed', 'saved', 'profile'] as const).map((item) => <Button key={item} title={item === 'saved' ? 'Saved' : item[0].toUpperCase() + item.slice(1)} onPress={() => setTab(item)} color={tab === item ? '#0E7490' : '#64748B'} />)}</View>{tab === 'feed' ? <><TextInput value={query} onChangeText={setQuery} placeholder="Search roles, companies, locations" style={styles.search} /><FlatList data={filtered} keyExtractor={(job) => job.jobId} renderItem={({ item }) => <JobCard job={item} onOpen={() => Alert.alert(item.title, `${item.company}\n${item.location}`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Apply', onPress: () => void apply(item) }, { text: 'Official site', onPress: () => void WebBrowser.openBrowserAsync(item.applyUrl) }])} />} ListEmptyComponent={<Text style={styles.empty}>No open internships match your search.</Text>} /></> : tab === 'saved' ? <Applications applications={applications} jobs={jobs} token={token} onChanged={() => void load()} /> : <Profile token={token} onSignOut={async () => { await sessionStorage.clear(); setToken(undefined); }} />}</SafeAreaView>;
}

function Onboarding({ token, onDone }: { token: string; onDone: () => void }) { const [selected, setSelected] = useState<string[]>(['swe']); const [keywords, setKeywords] = useState(''); const [saving, setSaving] = useState(false); const toggle = (category: string) => setSelected((current) => current.includes(category) ? current.filter((item) => item !== category) : [...current, category]); const complete = async () => { setSaving(true); try { const pushToken = await registerForJobAlerts(token); await api('/me/preferences', token, { method: 'PUT', body: JSON.stringify({ filter: { includeCategories: selected, includeKeywords: keywords.split(',').map((item) => item.trim()).filter(Boolean) }, alertsEnabled: Boolean(pushToken), onboardingComplete: true }) }); onDone(); } finally { setSaving(false); } }; return <SafeAreaView style={styles.onboarding}><Text style={styles.hero}>Make InternNotifs yours.</Text><Text style={styles.muted}>Choose the kinds of roles you want. You can edit these anytime.</Text><View style={styles.chips}>{categories.map((category) => <TouchableOpacity key={category} style={[styles.chip, selected.includes(category) && styles.chipOn]} onPress={() => toggle(category)}><Text>{category.toUpperCase()}</Text></TouchableOpacity>)}</View><TextInput style={styles.search} value={keywords} onChangeText={setKeywords} placeholder="Keywords, comma separated (optional)" /><Button title={saving ? 'Saving…' : 'Enable alerts & continue'} disabled={saving} onPress={() => void complete()} /></SafeAreaView> }
function Applications({ applications, jobs, token, onChanged }: { applications: Application[]; jobs: Job[]; token: string; onChanged: () => void }) { return <FlatList style={styles.list} data={applications} keyExtractor={(item) => item.applicationId} renderItem={({ item }) => { const job = jobs.find((candidate) => candidate.jobId === item.jobId); return <View style={styles.card}><Text style={styles.company}>{job?.company ?? 'Internship'}</Text><Text style={styles.title}>{job?.title ?? item.jobId}</Text><Text style={styles.muted}>{item.status.toUpperCase()}</Text><Button title="Advance status" onPress={() => void api(`/me/applications/${item.applicationId}`, token, { method: 'PATCH', body: JSON.stringify({ status: item.status === 'saved' ? 'applied' : 'interview' }) }).then(onChanged)} /></View>; }} ListEmptyComponent={<Text style={styles.empty}>Save roles or start an application to track them here.</Text>} /> }
function Profile({ token, onSignOut }: { token: string; onSignOut: () => void }) { const [profile, setProfile] = useState<Record<string, unknown>>({}); const [loading, setLoading] = useState(true); useEffect(() => { void api<Record<string, unknown> | null>('/me/profile', token).then((value) => setProfile(value ?? {})).finally(() => setLoading(false)); }, [token]); if (loading) return <ActivityIndicator style={styles.center} />; const contact = profile.contact as { name?: string; email?: string } | undefined; const uploadResume = async () => { const result = await DocumentPicker.getDocumentAsync({ type: ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'] }); if (result.canceled) return; const asset = result.assets[0]; const response = await api<{ document: { documentId: string }; uploadUrl: string }>('/me/documents', token, { method: 'POST', body: JSON.stringify({ fileName: asset.name, contentType: asset.mimeType ?? 'application/pdf' }) }); const file = await fetch(asset.uri); await fetch(response.uploadUrl, { method: 'PUT', headers: { 'Content-Type': asset.mimeType ?? 'application/pdf', 'x-amz-server-side-encryption': 'aws:kms' }, body: await file.blob() }); setProfile((current) => ({ ...current, resumeDocumentId: response.document.documentId })); Alert.alert('Résumé uploaded', 'Save your profile to attach it.'); }; return <ScrollView style={styles.list}><Text style={styles.hero}>Application profile</Text><TextInput style={styles.search} placeholder="Full name" value={contact?.name ?? ''} onChangeText={(name) => setProfile({ ...profile, contact: { ...contact, name } })} /><TextInput style={styles.search} placeholder="Email" value={contact?.email ?? ''} onChangeText={(email) => setProfile({ ...profile, contact: { ...contact, email } })} /><TextInput style={styles.search} placeholder="Location" value={profile.location as string ?? ''} onChangeText={(location) => setProfile({ ...profile, location })} /><TextInput style={styles.search} placeholder="Work authorization" value={profile.workAuthorization as string ?? ''} onChangeText={(workAuthorization) => setProfile({ ...profile, workAuthorization })} /><Button title={profile.resumeDocumentId ? 'Replace résumé' : 'Upload résumé'} onPress={() => void uploadResume()} /><View style={styles.spacer} /><Button title="Save profile" onPress={() => void api('/me/profile', token, { method: 'PUT', body: JSON.stringify({ ...profile, links: profile.links ?? {}, education: profile.education ?? [], reusableAnswers: profile.reusableAnswers ?? {} }) }).then(() => Alert.alert('Saved'))} /><View style={styles.spacer} /><Button title="Sign out" color="#B91C1C" onPress={onSignOut} /></ScrollView> }
function SignIn({ onSession }: { onSession: (token: string) => void }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [code, setCode] = useState(''); const [needsConfirmation, setNeedsConfirmation] = useState(false); const [busy, setBusy] = useState(false); const run = async (action: () => Promise<void>) => { setBusy(true); try { await action(); } catch (error) { Alert.alert('Account', error instanceof Error ? error.message : 'Please try again.'); } finally { setBusy(false); } }; return <SafeAreaView style={styles.onboarding}><Text style={styles.hero}>InternNotifs</Text><Text style={styles.muted}>{needsConfirmation ? 'Enter the email verification code Cognito sent you.' : 'Sign in or create an email-verified account.'}</Text><TextInput autoCapitalize="none" keyboardType="email-address" style={styles.search} placeholder="Email" value={email} onChangeText={setEmail} />{needsConfirmation ? <><TextInput keyboardType="number-pad" style={styles.search} placeholder="Verification code" value={code} onChangeText={setCode} /><Button title={busy ? 'Verifying…' : 'Verify email'} disabled={busy} onPress={() => void run(async () => { await confirmEmail(email, code); setNeedsConfirmation(false); Alert.alert('Verified', 'You can sign in now.'); })} /></> : <><TextInput secureTextEntry style={styles.search} placeholder="Password" value={password} onChangeText={setPassword} /><Button title={busy ? 'Signing in…' : 'Sign in'} disabled={busy} onPress={() => void run(async () => onSession(await signIn(email, password)))} /><View style={styles.spacer} /><Button title="Create account" onPress={() => void run(async () => { await signUp(email, password); setNeedsConfirmation(true); })} /></>}</SafeAreaView> }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#F8FAFC' }, center: { flex: 1, justifyContent: 'center', alignItems: 'center' }, nav: { flexDirection: 'row', justifyContent: 'space-around', paddingVertical: 8, backgroundColor: '#FFF' }, list: { flex: 1, padding: 16 }, card: { backgroundColor: '#FFF', padding: 16, marginHorizontal: 16, marginVertical: 6, borderRadius: 12, shadowColor: '#0F172A', shadowOpacity: 0.08, shadowRadius: 8, elevation: 2 }, company: { color: '#0E7490', fontWeight: '700' }, title: { fontSize: 17, fontWeight: '700', marginTop: 3 }, muted: { color: '#64748B', marginTop: 4 }, pay: { marginTop: 8, color: '#166534' }, search: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 10, padding: 12, margin: 12 }, empty: { textAlign: 'center', color: '#64748B', padding: 28 }, onboarding: { flex: 1, justifyContent: 'center', padding: 24, backgroundColor: '#F8FAFC' }, hero: { fontSize: 28, fontWeight: '800', color: '#0F172A', marginBottom: 10 }, chips: { flexDirection: 'row', flexWrap: 'wrap', marginVertical: 14, gap: 8 }, chip: { borderWidth: 1, borderColor: '#CBD5E1', padding: 10, borderRadius: 20 }, chipOn: { backgroundColor: '#A5F3FC', borderColor: '#0E7490' }, spacer: { height: 24 } });
